services:
  # El Gran Portero
  proxy:
    image: nginx:alpine
    container_name: emerald_global_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env  # Inyecta dinámicamente PROD_DOMAIN, STAGING_DOMAIN, DEV_DOMAIN, etc.
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      # Agregamos la carpeta de origen como solo lectura para que los symlinks resuelvan
      - ./nginx/templates-available:/etc/nginx/templates-available:ro
      - ./nginx/templates-enabled:/etc/nginx/templates # Solo lee lo que activamos vía symlink
    networks:
      - emerald_gateway

  # El Gestor de SSL
  certbot:
    image: certbot/certbot
    container_name: emerald_global_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  emerald_gateway:
    external: true