version = 5.6.0
archive_dir = /etc/letsencrypt/archive/emerald.2finternet.ar
cert = /etc/letsencrypt/live/emerald.2finternet.ar/cert.pem
privkey = /etc/letsencrypt/live/emerald.2finternet.ar/privkey.pem
chain = /etc/letsencrypt/live/emerald.2finternet.ar/chain.pem
fullchain = /etc/letsencrypt/live/emerald.2finternet.ar/fullchain.pem
[renewalparams]
account = 54b1c30309a62d130c1a4ec1aa26b59c
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
emerald-dev.2finternet.ar = /var/www/certbot
emerald-test.2finternet.ar = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2026-05-30T21:05:06
